### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by xaionaro** [Banno/getsentry-ldap-auth#27]
Is there any documentation explains how to install the plugin?

(especially if the instance is made by following https://github.com/getsentry/onpremise)

**Comment by heitorsilva** [comment]
hello @xaionaro!

It seems it doesn't, and to install it, after creating a Python virtual environment for Sentry (`mkvirtualenv sentry -p /usr/local/bin/python2.7` for example), you can do `pip install https://github.com/Banno/getsentry-ldap-auth/archive/2.5.zip` (select the plugin version by [visiting the releases list](https://github.com/Banno/getsentry-ldap-auth/releases)).

With the plugin installed by pip, then you have to configure `sentry.conf.py` with all the things that are described on [README.md](https://github.com/Banno/getsentry-ldap-auth/blob/master/README.md), matching your LDAP parameters.

Start (or restart) the server after all this, and it should be working.

Did I miss anything @barronhagerman?

**Comment by barronhagerman** [comment]
Yeah, sorry about that, @xaionaro. Thanks @heitorsilva. That pretty much covers it, which I suppose is why there's nothing about it in the README. I'll add some basic installation instructions.
