### ISSUE TITLE
Sentry 10 Installations fails with getsentry-ldap-auth

### ISSUE THREAD

**Issue by RogerSik** [Banno/getsentry-ldap-auth#46]
Like always added "sentry-ldap-auth" to requierements.txt and started install.sh from Sentry getting following error (file attached because of many lines). 

[commandline.txt](https://github.com/Banno/getsentry-ldap-auth/files/4344351/commandline.txt)

Without "sentry-ldap-auth" install.sh is succeeding.

**Comment by RogerSik** [comment]
Following i needed to add to Dockerfile for Sentry 10

~~~
# Install dependencies for LDAP authentication
RUN apt-get update && apt-get install -y build-essential libsasl2-dev python-dev libldap2-dev libssl-dev
~~~

Now it works :D

**Comment by janLo** [comment]
I'm just planning to upgrade a 9.x installation, @RogerSik can you confirm, that the plugin still works with Sentry 10?

**Comment by RogerSik** [comment]
@janLo still works 👌
