### ISSUE TITLE
Add external dependencies to README

### ISSUE THREAD

**Issue by prawn-cake** [Banno/getsentry-ldap-auth#7]
Please add external package dependencies to README

This package has the following external dependencies:
- libsasl2-dev
- python-dev
- libldap2-dev 
- libssl-dev

**Comment by ChadKillingsworth** [comment]
This project has exactly 2 dependencies: 
1. django-auth-ldap>=1.2.5
2. sentry>=8.0.0

Those packages have their own dependencies, but listing those here isn't really productive or maintainable.

Why would you even want this?

**Comment by prawn-cake** [comment]
Because when somebody taking it into use he or she relies on the project owner and if it doesn't work it frustrates.
Putting few lines to README how to install `pip install my_library` and mentioning some external dependencies if there are, it's not a big deal and might save time for others =)

**Comment by ChadKillingsworth** [comment]
So I'm trying to find where those dependencies are referenced - or even where the install instructions for django-auth-ldap are. Everywhere I find seems to assume "pip install" takes care of it.

**Comment by bibby** [comment]
On a fresh debian/ubuntu system (docker, aws, digital ocean, etc),  `python-ldap` doesn't install without the packages mentioned. For CentOs, the package names are different but the requirements are similar.

imho, this isn't your responsibility (Chad), but that of maintainers of `python-ldap` if anyone at all.

Repro steps for docker:

```
$ docker run -it ubuntu:latest
# in the container
$ apt-get update && apt-get install -y python-pip
$ pip install python-ldap
# breaks, Python.h
$ apt-get install -y python-dev && pip install python-ldap
# breaks, lber.h
$ apt-get install -y libldap2-dev && pip install python-ldap
# breaks, sasl.h
$ apt-get install -y libsasl2-dev && pip install python-ldap
# finally installed.
```

If it didn't happen with sentry, it would have happened with the next ldap-enabled python service.

**Comment by prawn-cake** [comment]
I can reassure you that it's reproduced not only on fresh systems, the packages are not common for daily usage.
Good practice is to test what you are releasing beforehand, especially if it's opensource.

It doesn't seem to me as a good idea to check all external dependencies for all project dependencies. It's just not developer-friendly. Can you imagine checking dozens of dependent packages on it's external dependencies? =)

So, just putting few lines in the README will improve quality of a project a lot ;)

**Comment by ChadKillingsworth** [comment]
> It doesn't seem to me as a good idea to check all external dependencies for all project dependencies.

I would firmly recommend against that.

I have no problems putting a line in the readme saying that this package requires python-ldap to be installed and functioning. I would also agree that the process for installing python-ldap is poorly documented. That team should do a much better job. However, listing specific libraries for dependencies 3 levels nested from this repository just isn't maintainable.

Case in point: the django-auth-ldap project doesn't list any of these steps either. It does mention the dependency on python-ldap however: https://bitbucket.org/psagers/django-auth-ldap/overview

**Comment by prawn-cake** [comment]
I got your point.
In real to answer on question whether it is maintainable or not you firstly need to estimate how volatile those dependencies are. If it uses _python-ldap_ since first release, then I guess no real reasons to reinvent the wheel and rewrite or change those dependencies for _django-ldap-auth_ guys, so then you literally spend 0 man-hours to maintain it.
In worst case somebody report you about some problems. You can also write integration tests with docker and run with travis ([for example](https://github.com/prawn-cake/pgclient#system-test)) and it notifies you if something wrong, so you will be sure that your project works correctly.

It's up to you, I just pointed to some issue. I believe when anybody takes some library from opensource and when it works out-of-the-box it brings more trust to a project owner ;)

**Comment by EvaSDK** [comment]
In all fairness, this would be an issue with django-ldap-auth, not with this project itself.
Using python ldap3 package would get rid of the problem altogether as it is a pure python client.
See https://bitbucket.org/psagers/django-auth-ldap/pull-requests/20/switched-to-python3-ldap/diff for that.

**Comment by ChadKillingsworth** [comment]
Based on this discussion I'm closing this issue. It has little to do with this plugin directly.
